# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd8f55cc9c5292462307b35ddee598b078689eb85f8a571020668102463aea41164c2e12302c4551cf322e4d23fae7af15096356f73948251abac36d8682c639

test:
  secret_key_base: ec520e9abdbfd6971b0c25b129f805310a5673805e8150c7b58eae0b1c3a1b86ef18250bc29029ec01cf6be4b6559f5039fd15fcbefd711e594492123af0b0a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
